apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
commonLabels:
  lechaterrant.com/app: argocd
  lechaterrant.com/stack: argocd
bases:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
resources:
  - argocd.namespace.yaml
  - argocd.ingress.yaml
  - argocd.projects.yaml
  - argocd.applications.yaml
patchesStrategicMerge:
  - argocd-cmd-params-cm.patch.yaml
  - argocd-cm.patch.yaml
  - argocd-rbac-cm-patch.yml
  - argocd.secret.patch.yaml
